# Generated by Selenium IDE
import unittest
from  selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities
from selenium.webdriver.firefox.options import Options

class BaseTest(unittest.TestCase):
  def setUp(self):
    geckodriver_path = "/snap/bin/geckodriver"
    options = Options()
    options.add_argument('--no-sandbox')
    options.add_argument('--disable-dev-shm-usage')
    driver_service = webdriver.FirefoxService(options=options, executable_path=geckodriver_path)

    self.driver = webdriver.Firefox(service=driver_service)
    self.vars = {}
  
  def tearDown(self):
    self.driver.quit()
  

if __name__ == '__main__':
  unittest.main()
