# Generated by Selenium IDE
import unittest
from  selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities
from selenium.webdriver.firefox.options import Options

class TestDemo(unittest.TestCase):
  def setUp(self):
    options = Options()
    options.add_argument('--no-sandbox')
    options.add_argument('--disable-dev-shm-usage')
    self.driver = webdriver.Remote(command_executor='http://javacream.eu:4444', options=options)
    self.wait = WebDriverWait(self.driver, 10)
    self.vars = {}
  
  def tearDown(self):
    self.driver.quit()
  
  def test_title_is_Javacream(self):
    self.driver.get("http://javacream.org/")
    self.driver.set_window_size(1120, 692)
    self.assertEqual('Javacream', self.driver.title)

if __name__ == '__main__':
  unittest.main()
